import { BlockMetadata } from '../../../features/DetailedView/types';

type Meta = Record<string, BlockMetadata[]>;

export const meta: Meta = {
  'start-exploitation': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2268, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2267, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2269, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3865, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв. км' },
    { id: 2265, name: 'Date', code: 'DATA_EXPL', type: 'date', title: 'Дата ввода в эксплуатацию' },
  ],
  categories: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2016, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2017, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2018, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2307, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 2022, name: 'Name', code: 'CATEGORY', type: 'string', title: 'Категория', hasDate: true },
    {
      id: 3883,
      name: 'CategorySp',
      code: 'CATEGORY_SP',
      type: 'string',
      title: 'Категория по СНиП 2.07.01-89',
      hasDate: true,
    },
    // { id: 0, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 0, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    // { id: 0, name: 'EntityPp', code: 'ENTITY_PP', type: 'string', title: '' },
  ],
  'number-of-lanes': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2207, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2208, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2209, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3871, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 0,
      name: 'Count',
      code: 'NUMBER_OF_STRIPES',
      type: 'number',
      title: 'Количество полос, шт',
      hasDate: true,
    },
    // { id: 3480, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 3479, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    // {
    //   id: 3859,
    //   name: 'Direction',
    //   code: 'DIRECTION_OF_TRAVEL',
    //   type: 'string',
    //   title: 'Направление',
    // },
  ],
  'type-of-coatings': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2212, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2213, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2214, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2240, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 2215, name: 'Coating', code: 'COATING', type: 'string', title: 'Вид покрытия', hasDate: true },
    // { id: 0, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 0, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    // {
    //   id: 0,
    //   name: 'Direction',
    //   code: 'DIRECTION_OF_TRAVEL',
    //   type: 'string',
    //   title: 'Направление',
    // },
  ],
  'road-class': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2226, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2227, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2224, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3872,
      name: 'Square',
      code: 'SQUARE',
      type: 'number',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '17rem',
    },
    {
      id: 2222,
      name: 'RoadClass',
      code: 'CLASS_OF_ROAD',
      type: 'string',
      title: 'Класс',
      hasDate: true,
      width: '13rem',
    },
    // { id: 0, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 0, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
  ],
  'axle-loads': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2004, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2005, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2006, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3873,
      name: 'Square',
      code: 'SQUARE',
      type: 'number',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '17rem',
    },
    { id: 3673, name: 'Os', code: 'OS', type: 'string', title: 'Нагрузка на ось, тонн/ось', hasDate: true },
    {
      id: 0,
      name: 'File',
      code: 'FILE',
      type: 'file',
      title: 'Документы, подтверждающие значение расчетной нагрузки на ось',
    },
    // { id: 3480, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 3479, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    // {
    //   id: 3859,
    //   name: 'Direction',
    //   code: 'DIRECTION_OF_TRAVEL',
    //   type: 'string',
    //   title: 'Направление',
    // },
  ],
  'max-speeds': [
    { id: 2280, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2279, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2282, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3874,
      name: 'Square',
      code: 'SQUARE',
      type: 'number',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '17rem',
    },
    // { id: 3480, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 3479, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    { id: 3478, name: 'MaxSpeed', code: 'VALUE', type: 'number', title: 'Максимальная скорость, км/ч', hasDate: true },
    // {
    //   id: 3859,
    //   name: 'Direction',
    //   code: 'DIRECTION_OF_TRAVEL',
    //   type: 'string',
    //   title: 'Направление',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  throughputs: [
    { id: 2273, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2272, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2276, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3876,
      name: 'Square',
      code: 'SQUARE',
      type: 'number',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '17rem',
    },
    // { id: 3480, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 3479, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    {
      id: 3478,
      name: 'MaxBandwidth',
      code: 'VALUE',
      type: 'number',
      title: 'Максимальная пропускная способность, авт/сут',
      hasDate: true,
      width: '15rem',
    },
    // {
    //   id: 3859,
    //   name: 'Direction',
    //   code: 'DIRECTION_OF_TRAVEL',
    //   type: 'string',
    //   title: 'Направление',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'cross-subjects': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2028, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2029, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2030, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3915, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    // { id: 3480, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 3479, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    { id: 0, name: 'Subject', code: 'SUBJECT', type: 'region', title: 'Субъект РФ', hasDate: true },
  ],
  agglomerations: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 2032, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2033, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2034, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3914, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    // { id: 3480, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 3479, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    { id: 0, name: 'Name', code: 'FULL_NAME', type: 'agglomeration', title: 'Агломерация', hasDate: true },
  ],
  'bridge-construction': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 0, name: 'Name', code: 'FULL_NAME', type: 'string', title: 'Наименование' },
    { id: 4101, name: 'Start', code: 'START', type: 'string', title: 'Начало' },
    { id: 4102, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец' },
    { id: 4103, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, м' },
    { id: 4115, name: 'Region', code: 'REGION', type: 'string', title: 'Местоположение' },
    { id: 4120, name: 'Type', code: 'TYPE', type: 'string', title: 'Вид' },
    { id: 4104, name: 'BuildingDate', code: 'BUILDING_DATE', type: 'date', title: 'Дата постройки', hasDate: true },
    // { id: 4109, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
    {
      id: 4121,
      name: 'TechnicalCondition',
      code: 'TECHNICAL_CONDITION',
      type: 'string',
      title: 'Техническое состояние',
    },
    { id: 4122, name: 'TypeOfObstacle', code: 'TYPE_OF_OBSTACLE', type: 'string', title: 'Тип препятствия' },
    {
      id: 4106,
      name: 'IdentificationNumber',
      code: 'IDENTIFICATION_NUMBER',
      type: 'string',
      title: 'Идентификационный код',
    },
    {
      id: 4107,
      name: 'OverallDimensions',
      code: 'OVERALL_DIMENSIONS',
      type: 'number',
      title: 'Ширина мостового полотна, м',
    },
    { id: 4108, name: 'BalanceStoim', code: 'BALANCE_STOIM', type: 'number', title: 'Балансовая стоимость, тыс. руб' },
    // { id: 4116, name: 'District', code: 'PARENT_LEVEL_3', type: 'string', title: 'Район' },
    // { id: 4117, name: 'City', code: 'PARENT_LEVEL_4', type: 'string', title: 'Город' },
    // { id: 4118, name: 'Locality', code: 'PARENT_LEVEL_6', type: 'string', title: 'Населенный пункт' },
    // { id: 4119, name: 'PlanningStructure', code: 'PARENT_LEVEL_65', type: 'string', title: 'Планировочная структура' },
    // { id: 4105, name: 'IsChecked', code: 'IS_CHECKED', type: 'boolean', title: 'Проверено' },
    // { id: 4255, name: 'ObstacleName', code: 'OBSTACLE_NAME', type: 'string', title: 'Наименование препятствия' },
    // { id: 4223, name: 'BridgeType1', code: 'BRIDGE_TYPE_1', type: 'string', title: 'Тип моста' },
    // { id: 4224, name: 'LocationType', code: 'LOCATION_TYPE', type: 'string', title: 'Тип расположения' },
    // { id: 201, name: 'Owner', code: 'OWNER', type: 'string', title: 'Владелец' },
  ],
  'pedestrian-crossings': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
    { id: 3927, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    { id: 0, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 0, name: 'Type', code: 'TYPE_OF_CROSSWALK', type: 'string', title: 'Тип', hasDate: true },
    // { id: 0, name: 'DateStart', code: 'DATE_START', type: 'date', title: 'Дата начала' },
    // { id: 0, name: 'DateFinish', code: 'DATE_FINISH', type: 'date', title: 'Дата окончания' },
  ],
  'operating-organizations': [
    { id: 2245, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2244, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2246, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3860, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 0,
      name: 'Name',
      code: 'FULL_NAME',
      type: 'owner',
      title: 'Эксплуатирующая организация',
      hasDate: true,
    },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Вид документа-основания возникновения вещного права',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Основные реквизиты документа-основания',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'kilometer-pillars': [
    { id: 4032, name: 'Number', code: 'TYPE', type: 'number', title: '№ столба' },
    { id: 0, name: 'Location', code: 'LOCATION', type: 'number', title: 'Местоположение Cтолба' },
    { id: 0, name: 'Latitude', code: 'LATITUDE', type: 'number', title: 'Широта' },
    { id: 4034, name: 'Longtitude', code: 'LONGTITUDE', type: 'number', title: 'Долгота', hasDate: true },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'roadway-width': [
    { id: 3861, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3862, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3863, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3864, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 3478, name: 'Width', code: 'VALUE', type: 'number', title: 'Ширина, м', hasDate: true },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'traffic-intensities': [
    { id: 3880, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3878, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3882, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3881, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 3879,
      name: 'AccountingPoint',
      code: 'ACCOUNTING_POINT',
      type: 'string',
      title: 'Местоположение учетного пункта, км',
    },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Легковые',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Грузовые легкие',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'number',
    //   title: 'Грузовые средние',
    //   width: '20rem',
    //   children: [
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'Значение',
    //     },
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'В т. ч. автопоезда',
    //     },
    //   ],
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'number',
    //   title: 'Грузовые тяжелые',
    //   width: '20rem',
    //   children: [
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'Значение',
    //     },
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'В т. ч. автопоезда',
    //     },
    //   ],
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'number',
    //   title: 'Грузовые сверхтяжелые',
    //   width: '20rem',
    //   children: [
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'Значение',
    //     },
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'В т. ч. автопоезда',
    //     },
    //   ],
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Автобусы',
    //   width: '20rem',
    // },
    {
      id: 3478,
      name: 'TrafficIntensity',
      code: 'VALUE',
      type: 'number',
      title: 'Среднесуточная интенсивность движения, авт/сут',
      hasDate: true,
    },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'increased-maintenance-complexity': [
    { id: 3901, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3902, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3903, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3904, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 4094,
      name: 'NatureOfSites',
      code: 'NATURE_OF_SITES',
      type: 'string',
      title: 'Характер участков',
      hasDate: true,
    },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'regulatory-statuses': [
    { id: 3495, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3496, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3497, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3920, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 3476, name: 'PlanFact', code: 'PLAN_FACT', type: 'boolean', title: 'План\\факт' },
    {
      id: 0,
      name: 'Value',
      code: 'VALUE',
      type: 'number',
      title: 'Значение',
      width: '10rem',
      children: [
        {
          id: 3478,
          name: 'LengthValue',
          code: 'VALUE',
          type: 'number',
          title: 'км',
        },
        {
          id: 3886,
          name: 'NormPercentage',
          code: 'NORM_PERCENTAGE',
          type: 'number',
          title: '%',
        },
      ],
    },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'photo-video-violation-fixation': [
    { id: 4420, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4425, name: 'InstallationLocation', code: 'INSTALLATION_LOCATION', type: 'string', title: 'Расположение' },
    { id: 4426, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Направление' },
    { id: 4427, name: 'Type', code: 'TYPE', type: 'violationFixation', title: 'Тип' },
    { id: 4416, name: 'SerialNumber', code: 'SERIAL_NUMBER', type: 'string', title: 'Серийный номер' },
    { id: 4421, name: 'InstallationDate', code: 'INSTALLATION_DATE', type: 'date', title: 'Дата установки' },
    { id: 4424, name: 'InstallationReason', code: 'INSTALLATION_REASON', type: 'string', title: 'Причина установки' },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  lightning: [
    { id: 2012, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2013, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2014, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 0, name: 'PropCount', code: 'VALUE', type: 'number', title: 'Количество опор, шт.' },
    {
      id: 2024,
      name: 'DefectPropCount',
      code: 'DEFECT_PROP_COUNT',
      type: 'number',
      title: 'Количество опор с дефектами, шт.',
    },
    {
      id: 2025,
      name: 'LightCount',
      code: 'LIGHT_COUNT',
      type: 'number',
      title: 'Количество светильников, шт.',
      hasDate: true,
    },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'traffic-lights': [
    { id: 3973, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    { id: 4045, name: 'InstallationLocation', code: 'INSTALLATION_LOCATION', type: 'string', title: 'Место установки' },
    { id: 4046, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'number',
    //   title: 'Транспортные светофоры',
    //   width: '20rem',
    //   children: [
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'тип',
    //     },
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'количество, шт',
    //     },
    //   ],
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'number',
    //   title: 'Пешеходные светофоры',
    //   width: '20rem',
    //   children: [
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'тип',
    //     },
    //     {
    //       id: 0,
    //       name: 'Blank',
    //       code: 'BLANK',
    //       type: 'number',
    //       title: 'количество, шт',
    //     },
    //   ],
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Расположение',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Вид опоры',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'road-stops': [
    { id: 3974, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    { id: 4138, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 0, name: 'Name', code: 'FULL_NAME', type: 'string', title: 'Наименование' },
    { id: 3976, name: 'Pocket', code: 'POCKET', type: 'boolean', title: 'Наличие кармана' },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Наличие элементов',
    //   width: '20rem',
    // },
    { id: 4137, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  stations: [
    { id: 3993, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4140, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4052, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'gas-stations': [
    { id: 3995, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4141, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4053, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип' },
    { id: 0, name: 'Organization', code: 'ORGANIZATION', type: 'owner', title: 'Организация', hasDate: true },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Вид',
    //   width: '20rem',
    // },

    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Количество заправочных колонок, шт',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Площадь, кв. м',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Принадлежность',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'service-stations': [
    { id: 3997, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4142, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4054, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Расстояние от дороги, м',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Количество постов на СТО, шт',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Принадлежность',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  platforms: [
    { id: 3977, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4413, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 4143, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4047, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип' },
    { id: 4048, name: 'Coating', code: 'COATING', type: 'string', title: 'Вид покрытия', hasDate: true },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Оборудование',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Принадлежность',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  sidewalks: [
    { id: 3979, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 0, name: 'Finish', code: 'Finish', type: 'string', title: 'Конец участка, км+м' },
    { id: 4144, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4049, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 3982, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3983, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия, кв.м' },
    { id: 3984, name: 'Width', code: 'WIDTH', type: 'number', title: 'Ширина, м' },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'medical-institutions': [
    { id: 4189, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4190, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    // { id: 0, name: 'Name', code: 'NAME', type: 'owner', title: 'Наименование', hasDate: false },
    { id: 4192, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 4191, name: 'EmergencyRoom', code: 'EMERGENCY_ROOM', type: 'boolean', title: 'Наличие травмпункта' },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Расстояние от дороги, м',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Принадлежность',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'vacation-spots': [
    { id: 3999, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4145, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4055, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Расстояние от дороги, м',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Название',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Принадлежность',
    //   width: '20rem',
    // },
    { id: 5383, name: 'Url', code: 'URL', type: 'string', title: 'Сайт' },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'local-treatment-buildings': [
    { id: 3985, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    { id: 4050, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Расположение',
    //   width: '20rem',
    // },
    // {
    //   id: 4672,
    //   name: 'Region',
    //   code: 'REGION',
    //   type: 'string',
    //   title: 'Субъект РФ',
    // },
    { id: 3986, name: 'Quantity', code: 'QUANTITY', type: 'number', title: 'Количество' },
    { id: 3987, name: 'Perfomance', code: 'PERFORMANCE', type: 'number', title: 'Производительность, л/ч' },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Техническое состояние',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Фотоматериалы',
    //   width: '20rem',
    // },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Техническая документация',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'terrain-types': [
    { id: 4077, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 4078, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 4079, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 4089,
      name: 'Name',
      code: 'HUMIDIFICATION_COND',
      type: 'string',
      title: 'Тип местности по условиям увлажнения',
      hasDate: true,
    },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'communication-intersections': [
    { id: 2292, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 2291, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 2294, name: 'Type', code: 'TYP_COM', type: 'string', title: 'Вид коммуникаций' },
    { id: 4036, name: 'Intersection', code: 'INTERSECTION', type: 'string', title: 'Место пересечения, км+м' },
    { id: 4037, name: 'Size', code: 'SIZE', type: 'number', title: 'Габарит проезда по ширине, м' },
    { id: 4329, name: 'HeightSize', code: 'HEIGHT_SIZE', type: 'number', title: 'Габарит проезда по высоте, м' },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Дата размещения сведений',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
  'railway-intersections': [
    { id: 4010, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 4011, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 4017, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 5376, name: 'Type', code: 'TYPE', type: 'string', title: 'Вид пересечения и положение автомобильной дороги' },
    { id: 4014, name: 'NumberOfPaths', code: 'NUMBER_OF_PATHS', type: 'number', title: 'Количество путей, шт' },
    { id: 4045, name: 'Name', code: 'FULL_NAME', type: 'string', title: 'Наименование ж/д направления' },
    { id: 4015, name: 'Size', code: 'SIZE', type: 'number', title: 'Габарит проезда по ширине, м' },
    { id: 4331, name: 'HeightSize', code: 'HEIGHT_SIZE', type: 'number', title: 'Габарит проезда по высоте, м' },
    // {
    //   id: 0,
    //   name: 'Blank',
    //   code: 'BLANK',
    //   type: 'string',
    //   title: 'Дата размещения сведений',
    //   width: '20rem',
    // },
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: 'На карте', width: '7rem' },
  ],
};
