import { BlockMetadata } from '../../../features/DetailedView/types';

type Meta = Record<string, BlockMetadata[]>;

export const meta: Meta = {
  // Собственники, владельцы дороги и эксплуатирующие организации
  'road-owners': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2008, name: 'Start', code: 'START', type: 'roadStartSectionLink', title: 'Начало участка, км+м' },
    { id: 2009, name: 'Finish', code: 'FINISH', type: 'roadFinishSectionLink', title: 'Конец участка, км+м' },
    { id: 2010, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2420, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 2421, name: 'BalanceStoim', code: 'BALANCE_STOIM', type: 'number', title: 'Балансовая стоимость, тыс. руб.' },
    { id: 2422, name: 'Ostatok', code: 'OSTATOK', type: 'number', title: 'Остаточная стоимость, тыс. руб.' },
    {
      id: 201,
      name: 'Owner',
      code: 'OWNER',
      type: 'owner',
      externalKey: 'name',
      title: 'Полное наименование юридического лица / ФИО физического лица',
      width: '45rem',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид документа-основания возникновения вещного права',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Основные реквизиты документа-основания',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Наименование вещного права',
      width: '20rem',
    },
  ],
  'operating-organizations': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2245, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2244, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2246, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3860, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 0,
      name: 'Name',
      code: 'FULL_NAME',
      type: 'owner',
      externalKey: 'name',
      title: 'Полное наименование юридического лица',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид документа-основания возникновения вещного права',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Основные реквизиты документа-основания',
      width: '20rem',
    },
  ],

  // Нормативно-правовые документы
  regulations: [
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: '№ п/п',
    },
    { id: 0, name: 'Name', code: 'FULL_NAME', type: 'string', title: 'Наименование' },
    { id: 3165, name: 'RegNumber', code: 'REG_NUMBER', type: 'string', title: '№' },
    { id: 3156, name: 'RegDate', code: 'REG_DATE', type: 'date', title: 'Дата' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Уровень',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Статус',
    },
    {
      id: 3161,
      name: 'Description',
      code: 'DESCRIPTION',
      type: 'string',
      title: 'Орган системы управления',
    },
    { id: 0, name: 'File', code: 'FILE', type: 'file', title: 'Документ-основание' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата размещения сведений',
      width: '20rem',
    },
  ],
  // Выписки? Поручения?

  // Дополнительная информация об участках
  'backbone-network': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 5519, name: 'Start', code: 'START', type: 'roadStartBackboneNetwork', title: 'Начало участка, км+м' },
    { id: 5517, name: 'Finish', code: 'FINISH', type: 'roadFinishBackboneNetwork', title: 'Конец участка, км+м' },
    { id: 5518, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Категория критерия',
      width: '20rem',
    },
    { id: 5516, name: 'Criterion', code: 'CRITERION', type: 'string', title: 'Критерии опорной сети', hasDate: true },
    { id: 5514, name: 'Itr', code: 'ITR', type: 'string', title: 'МТМ' },
  ],
  'start-exploitation': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2268, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2267, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2269, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2265, name: 'Date', code: 'DATA_EXPL', type: 'date', title: 'Дата ввода в эксплуатацию' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид работ',
      width: '20rem',
    },
  ],
  'paid-section-of-the-road': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2051, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2052, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2060, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Местоположение пунктов взимания платы (ПВП)',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
    { id: 0, name: 'Tariff', code: 'OTHER', type: 'string', title: 'Тариф', hasDate: true },
  ],
  'overloaded-roads': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 1887, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 1888, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 1889, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Площадь покрытия проезжей части, кв.м',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
    // { id: 4358, name: 'Seasonality', code: 'SEASONALITY', type: 'string', title: 'Сезонность' },
    // { id: 4359, name: 'TimesOfDay', code: 'TIMES_OF_DAY', type: 'string', title: 'Время суток', hasDate: true },
  ],
  // @TODO прикрутить модалку!!!
  'dangerous-sections': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 1885, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 1886, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 1846, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
    {
      id: 1845,
      name: 'RegistrationDate',
      code: 'REGISTRATION_DATE',
      type: 'string',
      title: 'Дата регистрации',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата снятия с регистрации',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Наличие в ПКРТИ',
      titleHint: 'Наличие в программе комплексного развития транспортной инфраструктуры',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Недостатки транспортно-эксплуатационного состояния в местах совершения ДТП по карточкам учета по ДУ',
    },
    { id: 1646, name: 'Description', code: 'DESCRIPTION', type: 'string', title: 'Причина возникновения' },
    { id: 1890, name: 'DtpType', code: 'DTP_TYPE', type: 'string', title: 'Вид ДТП' },
    { id: 0, name: 'CountAccident', code: 'COUNT_ACCIDENT', type: 'number', title: 'Количество ДТП' },
    {
      id: 0,
      name: 'Injured',
      code: 'INJURED',
      type: 'number',
      title: 'Количество пострадавших',
      children: [
        {
          id: 0,
          name: 'Wounded',
          code: 'WOUNDED',
          type: 'number',
          title: 'Ранено',
        },
        {
          id: 0,
          name: 'Dead',
          code: 'DEAD',
          type: 'number',
          title: 'Погибло',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата размещения сведений',
      width: '20rem',
    },
  ],
  'increased-maintenance-complexity': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3901, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3902, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3903, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3904, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 4094,
      name: 'NatureOfSites',
      code: 'NATURE_OF_SITES',
      type: 'string',
      title: 'Характер участков',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
  ],

  // Местоположение
  'cross-subjects': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2028, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2029, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2030, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3915, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 123445555, name: 'Subject', code: 'SUBJECT', type: 'region', title: 'Субъект РФ', hasDate: true },
  ],
  agglomerations: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2032, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2033, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2034, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3914, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 123, name: 'Name', code: 'FULL_NAME', type: 'agglomeration', title: 'Городская агломерация', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
    {
      id: 5528,
      name: 'TypeLastWork',
      code: 'TYPE_LAST_WORK',
      type: 'string',
      title: 'Вид последних работ',
    },
    {
      id: 5526,
      name: 'LastDateWork',
      code: 'LAST_DATE_WORK',
      type: 'string',
      title: 'Дата последнего проведения работ',
    },
  ],
  'climatic-zones': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 0, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 0, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 0, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 4090,
      name: 'Name',
      code: 'CLIMATIC_ZONE',
      type: 'string',
      title: 'Дорожно-климатическая зона',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
  ],
  'terrain-types': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4077, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 4078, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 4079, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 4089,
      name: 'Name',
      code: 'HUMIDIFICATION_COND',
      type: 'string',
      title: 'Тип местности по условиям увлажнения',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Субъект РФ',
    },
  ],

  //Общие технические данные
  'max-speeds': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2280, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2279, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2282, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3478,
      name: 'MaxSpeed',
      code: 'VALUE',
      type: 'number',
      title: 'Максимальная разрешенная скорость, км/ч',
      hasDate: true,
    },
  ],
  'axle-loads': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 0, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 0, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 0, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3673, name: 'Os', code: 'OS', type: 'string', title: 'Расчётная нагрузка на ось, Мпа', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Максимальный вес на двойную ось транспортного средства',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Максимальный вес на тройную ось транспортного средства',
      width: '20rem',
    },
    {
      id: 0,
      name: 'File',
      code: 'FILE',
      type: 'file',
      title: 'Документы, подтверждающие значение расчетной нагрузки на ось',
      width: '20rem',
    },
  ],
  throughputs: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2273, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2272, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2276, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3478,
      name: 'MaxBandwidth',
      code: 'VALUE',
      type: 'number',
      title: 'Пропускная способность, авт/сут',
      hasDate: true,
      width: '15rem',
    },
  ],
  'traffic-intensities': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3880, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3878, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3882, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3879,
      name: 'AccountingPoint',
      code: 'ACCOUNTING_POINT',
      type: 'string',
      title: 'Местоположение учетного пункта, км',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Легковые',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Грузовые легкие',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Грузовые средние',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'Значение',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'В т. ч. автопоезда',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Грузовые тяжелые',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'Значение',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'В т. ч. автопоезда',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Грузовые сверхтяжелые',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'Значение',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'В т. ч. автопоезда',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Автобусы',
      width: '20rem',
    },
    {
      id: 3478,
      name: 'TrafficIntensity',
      code: 'VALUE',
      type: 'number',
      title: 'Среднесуточная интенсивность движения, авт/сут',
      hasDate: true,
    },
  ],
  'oversized-cargo-limitations': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4069, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    { id: 4070, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 4071, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 4083,
      name: 'NatureOfSites',
      code: 'NATURE_OF_SITES',
      type: 'string',
      title: 'Характер ограничения',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Sizings',
      code: 'SIZINGS',
      type: 'number',
      title: 'Габарит проезда',
      width: '35rem',
      children: [
        {
          id: 4186,
          name: 'Size',
          code: 'SIZE',
          type: 'number',
          title: 'По ширине, м',
        },
        {
          id: 4444,
          name: 'Height',
          code: 'HEIGHT_SIZE',
          type: 'number',
          title: 'По высоте, м',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'string',
          title: 'По длине, м',
        },
        {
          id: 4445,
          name: 'Weight',
          code: 'SIZE_SCALES',
          type: 'number',
          title: 'По весу, т',
        },
      ],
    },
    { id: 0, name: 'Other', code: 'OTHER', type: 'string', title: 'Реквизиты нормативно-правового документа' },
  ],

  // Проезжая часть и земляное полотно
  categories: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2016, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2017, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2018, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2307, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 2022, name: 'Name', code: 'CATEGORY', type: 'string', title: 'Техническая категория', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Рельеф местности',
      width: '20rem',
    },
    {
      id: 3883,
      name: 'CategorySp',
      code: 'CATEGORY_SP',
      type: 'string',
      title: 'Категория дороги (группа улицы) согласно СП 42.13330-2016',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расчетная скорость движения, км/ч',
      width: '20rem',
    },
  ],
  'road-class': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2226, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2227, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2224, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 3872,
      name: 'Square',
      code: 'SQUARE',
      type: 'number',
      title: 'Площадь покрытия проезжей части, кв.м',
      width: '17rem',
    },
    {
      id: 2222,
      name: 'RoadClass',
      code: 'CLASS_OF_ROAD',
      type: 'string',
      title: 'Класс',
      hasDate: true,
      width: '13rem',
    },
  ],
  'number-of-lanes': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2207, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2208, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2209, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3871, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 3478, name: 'Count', code: 'VALUE', type: 'number', title: 'Число полос движения на участке', hasDate: true },
  ],
  'roadway-width': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3861, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3862, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3863, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3864, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 3478, name: 'Width', code: 'VALUE', type: 'number', title: 'Ширина, м', hasDate: true },
  ],
  'earthen-canvas-width': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3866, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3867, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3868, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    // { id: 3869, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 3478,
      name: 'Width',
      code: 'VALUE',
      type: 'number',
      title: 'Ширина земляного полотна поверху, м',
      hasDate: true,
    },
    {
      id: 3870,
      name: 'CoverageArea',
      code: 'COVERAGE_AREA',
      type: 'number',
      title: 'Площадь земляного полотна поверху, кв.м',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Высота насыпи/глубина выемки',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'справа, м',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'слева, м',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Заложение откосов',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'справа',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'слева',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Грунт земляного полотна',
      width: '20rem',
    },
  ],
  'type-of-coatings': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2212, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2213, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2214, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2240, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Тип дорожной одежды ',
      width: '20rem',
    },
    {
      id: 2215,
      name: 'Coating',
      code: 'COATING',
      type: 'string',
      title: 'Вид покрытия',
      hasDate: true,
      width: '13rem',
    },
  ],

  // Пересечения
  'communication-intersections': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    // { id: 2292, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    // { id: 2291, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    { id: 4036, name: 'Intersection', code: 'INTERSECTION', type: 'string', title: 'Место пересечения, км+м' },
    { id: 2294, name: 'Type', code: 'TYP_COM', type: 'string', title: 'Вид коммуникаций' },
    { id: 4037, name: 'Size', code: 'SIZE', type: 'number', title: 'Габарит проезда по ширине, м' },
    { id: 4329, name: 'HeightSize', code: 'HEIGHT_SIZE', type: 'number', title: 'Габарит проезда по высоте, м' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата размещения сведений',
      width: '20rem',
    },
  ],
  'road-intersections': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    // { id: 2577, name: 'Start', code: 'LOCATION_START', type: 'string', title: 'Начало участка' },
    // { id: 2576, name: 'Finish', code: 'LOCATION_END', type: 'string', title: 'Конец участка' },
    { id: 4082, name: 'Intersection', code: 'INTERSECTION', type: 'string', title: 'Место пересечения, км+м' },
    // { id: 2573, name: 'Length', code: 'LENGTH_POPIKETNO', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Name',
      code: 'FULL_NAME',
      type: 'roadLink',
      title: 'Пересекаемая/примыкающая автомобильная дорога',
    },
    { id: 2219, name: 'LevelsCount', code: 'NUMBER_OF_LEVELS', type: 'number', title: 'Количество уровней' },
    { id: 4081, name: 'Size', code: 'SIZE', type: 'number', title: 'Габарит проезда по ширине, м' },
    { id: 4330, name: 'HeightSize', code: 'HEIGHT_SIZE', type: 'number', title: 'Габарит проезда по высоте, м' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата размещения сведений',
      width: '20rem',
    },
  ],
  'railway-intersections': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    // { id: 4010, name: 'Start', code: 'START', type: 'string', title: 'Начало участка' },
    // { id: 4011, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка' },
    // { id: 4017, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Место пересечения, км+м',
      width: '20rem',
    },
    { id: 5376, name: 'Type', code: 'TYPE', type: 'string', title: 'Уровень пересечения' },
    { id: 4015, name: 'Size', code: 'SIZE', type: 'number', title: 'Габарит проезда по ширине, м' },
    { id: 4331, name: 'HeightSize', code: 'HEIGHT_SIZE', type: 'number', title: 'Габарит проезда по высоте, м' },
    { id: 4014, name: 'NumberOfPaths', code: 'NUMBER_OF_PATHS', type: 'number', title: 'Количество путей, шт' },
    { id: 4045, name: 'Name', code: 'FULL_NAME', type: 'string', title: 'Наименование ж/д направления' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата размещения сведений',
      width: '20rem',
    },
  ],
  'road-parts': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3911, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3912, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2367, name: 'Length', code: 'LENGTH_POPIKETNO', type: 'number', title: 'Протяженность, км' },
    { id: 2368, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 2359, name: 'Type', code: 'ROAD_LOCATION_TYPE', type: 'string', title: 'Тип участка', hasDate: true },
  ],

  // Элементы обустройства
  'traffic-lights': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3973, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    {
      id: 4045,
      name: 'InstallationLocation',
      code: 'INSTALLATION_LOCATION',
      type: 'string',
      title: 'Место установки',
      hasDate: true,
    },
    // { id: 4046, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Транспортные светофоры',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'тип',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'количество, шт',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'number',
      title: 'Пешеходные светофоры',
      width: '20rem',
      children: [
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'тип',
        },
        {
          id: 0,
          name: 'Blank',
          code: 'BLANK',
          type: 'number',
          title: 'количество, шт',
        },
      ],
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расположение',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид опоры',
      width: '20rem',
    },
  ],
  lightning: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2012, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2013, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    // { id: 2014, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 0, name: 'PropCount', code: 'VALUE', type: 'number', title: 'Количество опор, шт.' },
    {
      id: 2024,
      name: 'DefectPropCount',
      code: 'DEFECT_PROP_COUNT',
      type: 'number',
      title: 'Количество опор с дефектами, шт.',
    },
    {
      id: 2025,
      name: 'LightCount',
      code: 'LIGHT_COUNT',
      type: 'number',
      title: 'Количество светильников, шт.',
      hasDate: true,
    },
  ],
  'road-stops': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3974, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    { id: 4138, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 0, name: 'Name', code: 'FULL_NAME', type: 'string', title: 'Наименование' },
    // { id: 3976, name: 'Pocket', code: 'POCKET', type: 'boolean', title: 'Наличие кармана' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Наличие элементов',
      width: '20rem',
    },
    { id: 4137, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
  ],
  sidewalks: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3979, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 0, name: 'Finish', code: 'Finish', type: 'string', title: 'Конец участка, км+м' },
    { id: 3982, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3983, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия, кв.м' },
    { id: 4144, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4049, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 3984, name: 'Width', code: 'WIDTH', type: 'number', title: 'Ширина, м' },
  ],
  'soundproofing-buildings': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3988, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3989, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3991, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 4147, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4051, name: 'Type', code: 'TYPE', type: 'string', title: 'Вид', hasDate: true },
    { id: 3992, name: 'Height', code: 'HEIGHT', type: 'number', title: 'Высота сооружения, м' },
  ],
  barriers: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4332, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 4333, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 4334, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расположение',
      width: '20rem',
    },
    { id: 4339, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Материал',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Световозвращатель',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Высота, м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дефекты',
      width: '20rem',
    },
  ],
  // Синие блоки
  'kilometer-pillars': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4030, name: 'Number', code: 'POST_NUMBER', type: 'number', title: '№ столба' },
    // { id: 4032, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение столба' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние до следующего километрового знака, м',
      width: '20rem',
    },
    { id: 4034, name: 'Latitude', code: 'LATITUDE', type: 'string', title: 'Широта' },
    { id: 4035, name: 'Longtitude', code: 'LONGITUDE', type: 'string', title: 'Долгота', hasDate: true },
  ],

  // Объекты дорожного сервиса
  'gas-stations': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3995, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4141, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Границы размещения',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние от внешней границы обочины, м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Тип топлива ',
      width: '20rem',
    },
    { id: 4053, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Количество заправочных колонок, шт',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Площадь, кв. м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Принадлежность',
      width: '20rem',
    },
    { id: 0, name: 'Organization', code: 'ORGANIZATION', type: 'owner', title: 'Организация', hasDate: true },
  ],
  'service-stations': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3997, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4142, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение', hasDate: true },
    // { id: 4054, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Границы размещения ',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние от внешней границы обочины, м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Количество постов на СТО, шт',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Принадлежность',
      width: '20rem',
    },
  ],
  platforms: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3977, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4143, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Границы размещения',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние от внешней границы обочины, м',
      width: '20rem',
    },
    { id: 4047, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип' },
    {
      id: 4048,
      name: 'Coating',
      code: 'COATING',
      type: 'string',
      title: 'Вид покрытия',
      width: '13rem',
      hasDate: true,
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Количество машиномест',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Оборудование',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Принадлежность',
      width: '20rem',
    },
  ],
  stations: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3993, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4140, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    { id: 4052, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
  ],
  'vacation-spots': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3999, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4145, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Границы размещения',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние от внешней границы обочины, м',
      width: '20rem',
    },
    { id: 4055, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Наименование',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Принадлежность',
      width: '20rem',
    },
    { id: 5383, name: 'Url', code: 'URL', type: 'string', title: 'Интернет-сайт' },
  ],
  'weight-control-points': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    {
      id: 4381,
      name: 'Location',
      code: 'LOCATIONN',
      type: 'string',
      title: 'Местоположение, км+м',
    },
    {
      id: 4377,
      name: 'Direction',
      code: 'DIRECTION_OF_TRAVEL',
      type: 'string',
      title: 'Расположение',
    },
    {
      id: 0,
      name: 'Status',
      code: 'STATUS',
      type: 'string',
      title: 'Статус',
    },
    {
      id: 2754,
      name: 'Type',
      code: 'POST_TYPE',
      type: 'string',
      title: 'Тип ПВГК',
    },
    {
      id: 2751,
      name: 'Model',
      code: 'WEIGHT',
      type: 'number',
      title: 'Марка и модель весов',
      hasDate: true,
    },
    {
      id: 4378,
      name: 'AxleLoad',
      code: 'OS',
      type: 'string',
      title: 'Нагрузка на ось, тонн/ось',
    },
    {
      id: 0,
      name: 'BalanceHolder',
      code: 'BalanceHolder',
      type: 'owner',
      title: 'Балансодержатель',
    },
    {
      id: 0,
      name: 'OperatingOrganization',
      code: 'OperatingOrganization',
      type: 'owner',
      title: 'Эксплуатирующая организация',
    },
  ],
  'medical-institutions': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4189, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4190, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Границы размещения',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние от внешней границы обочины, м',
      width: '20rem',
    },
    { id: 0, name: 'Name', code: 'NAME', type: 'owner', title: 'Наименование', hasDate: false },
    { id: 4192, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 4191, name: 'EmergencyRoom', code: 'EMERGENCY_ROOM', type: 'boolean', title: 'Наличие травмпункта' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Принадлежность',
      width: '20rem',
    },
  ],
  'multifunctional-zones': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4001, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м', hasDate: true },
    { id: 4146, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Границы размещения',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расстояние от внешней границы обочины, м',
      width: '20rem',
    },
    { id: 4003, name: 'GasStationCount', code: 'AMOUNTOFGASSTATION', type: 'number', title: 'Количество АЗС, шт' },
    {
      id: 4004,
      name: 'ServiceStationCount',
      code: 'NUMBEROFSERVICESTATIONS',
      type: 'number',
      title: 'Количество СТО, шт',
    },
    {
      id: 4005,
      name: 'HotelsCount',
      code: 'NUMBEROFHOTELS',
      type: 'number',
      title: 'Количество гостиниц (мотелей, кемпингов), шт',
    },
    {
      id: 4006,
      name: 'FoodItemsCount',
      code: 'NUMBEROFFOODITEMS',
      type: 'number',
      title: 'Количество пунктов питания, шт',
    },
    {
      id: 4007,
      name: 'WashingItemsCount',
      code: 'NUMBEROFWASHINGPOINTS',
      type: 'number',
      title: 'Количество моечных пунктов, шт',
    },
    {
      id: 4008,
      name: 'ContactItemsCount',
      code: 'NUMBEROFPOINTSOFCONTACT',
      type: 'number',
      title: 'Количество пунктов связи, шт',
    },
    { id: 4009, name: 'StoresCount', code: 'NUMBEROFSTORES', type: 'number', title: 'Количество пунктов торговли, шт' },
    { id: 5384, name: 'Url', code: 'URL', type: 'string', title: 'Интернет-сайт' },
  ],

  // Нормативное / ненормативное состояние
  'regulatory-statuses': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3495, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 3496, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 3497, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3920, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 3476, name: 'PlanFact', code: 'PLAN_FACT', type: 'boolean', title: 'План\\факт' },
    {
      id: 0,
      name: 'Value',
      code: 'VALUE',
      type: 'number',
      title: 'Значение',
      width: '10rem',
      children: [
        {
          id: 3478,
          name: 'LengthValue',
          code: 'VALUE',
          type: 'number',
          title: 'км',
        },
        {
          id: 3886,
          name: 'NormPercentage',
          code: 'NORM_PERCENTAGE',
          type: 'number',
          title: '%',
        },
      ],
    },
  ],

  // Оценка технического состояния (результаты)
  diagnostics: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3488, name: 'Start', code: 'START', type: 'roadStartDiagnostics', title: 'Начало участка, км+м' },
    { id: 3489, name: 'Finish', code: 'FINISH', type: 'roadFinishDiagnostics', title: 'Конец участка, км+м' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Координаты начала участка',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Координаты конца участка',
      width: '20rem',
    },
    { id: 3490, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Дата проведения обследования',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Тип дорожно-климатической зоны',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Техническая категория',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Тип дорожной одежды',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Рельеф местности',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Итоговое нормативное состояние, км',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Итоговое нормативное состояние, %',
      width: '20rem',
    },
    // { id: 4093, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    // { id: 3504, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип диагностики' },
    // { id: 3476, name: 'PlanFact', code: 'PLAN_FACT', type: 'number', title: 'Статус', hasDate: true },
    // { id: 0, name: 'File', code: 'FILE', type: 'file', title: 'Документы, подтверждающие проведение диагностики' },
  ],

  // Искусственные сооружения
  'bridge-construction': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4105, name: 'IsChecked', code: 'IS_CHECKED', type: 'boolean', title: 'Проверено' },
    { id: 0, name: 'Name', code: 'FULL_NAME', type: 'bridgeLink', title: 'Наименование' },
    { id: 0, name: 'Id', code: 'ID', type: 'number', title: 'Номер СКДФ' },
    { id: 4101, name: 'Start', code: 'START', type: 'string', title: 'Начало, км+м' },
    { id: 4102, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец, км+м' },
    { id: 4120, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид материала',
      width: '20rem',
    },
    { id: 4122, name: 'TypeOfObstacle', code: 'TYPE_OF_OBSTACLE', type: 'string', title: 'Тип основного препятствия' },
    { id: 4103, name: 'Length', code: 'LENGTH', type: 'number', title: 'Полная длина, м' },
    {
      id: 4104,
      name: 'BuildingDate',
      code: 'BUILDING_DATE',
      type: 'date',
      title: 'Год ввода в эксплуатацию',
      hasDate: true,
    },
    {
      id: 4121,
      name: 'TechnicalCondition',
      code: 'TECHNICAL_CONDITION',
      type: 'string',
      title: 'Техническое состояние',
    },
    // Owner?
  ],
  pipes: [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4114, name: 'IsChecked', code: 'IS_CHECKED', type: 'boolean', title: 'Проверено' },
    { id: 0, name: 'Id', code: 'ID', type: 'number', title: 'Номер СКДФ' },
    { id: 4110, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    // { id: 4115, name: 'Location', code: '_LOCATION', type: 'location', title: 'Адрес' },
    { id: 4129, name: 'TypeOfPipe', code: 'PIPE_TYPE', type: 'string', title: 'Тип трубы' },
    { id: 4128, name: 'TypeOfObstacle', code: 'TYPE_OF_OBSTACLE', type: 'string', title: 'Тип основного препятствия' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Полная длина, м',
      width: '20rem',
    },
    // { id: 4111, name: 'RoadwayWidth', code: 'ROADWAY_WIDTH', type: 'number', title: 'Ширина проезжей части, м' },
    {
      id: 4112,
      name: 'BuildingDate',
      code: 'BUILDING_DATE',
      type: 'date',
      title: 'Год ввода в эксплуатацию',
      hasDate: true,
    },
    {
      id: 4127,
      name: 'TechnicalCondition',
      code: 'TECHNICAL_CONDITION',
      type: 'string',
      title: 'Техническое состояние',
    },
    // { id: 4113, name: 'BalanceStoim', code: 'BALANCE_STOIM', type: 'number', title: 'Балансовая стоимость, тыс. руб' },
  ],
  'local-treatment-buildings': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3985, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Расположение',
      width: '20rem',
    },
    {
      id: 4672,
      name: 'Region',
      code: 'REGION',
      type: 'string',
      title: 'Субъект РФ',
    },
    { id: 4050, name: 'Type', code: 'TYPE', type: 'string', title: 'Тип', hasDate: true },
    { id: 3986, name: 'Quantity', code: 'QUANTITY', type: 'number', title: 'Количество' },
    { id: 3987, name: 'Perfomance', code: 'PERFORMANCE', type: 'number', title: 'Производительность, л/ч' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Техническое состояние',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Фотоматериалы',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Техническая документация',
      width: '20rem',
    },
  ],
  'pedestrian-crossings': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 3927, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение' },
    // { id: 4139, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение' },
    {
      id: 4672,
      name: 'Region',
      code: 'REGION',
      type: 'string',
      title: 'Субъект РФ',
    },
    { id: 4043, name: 'Type', code: 'TYPE_OF_CROSSWALK', type: 'string', title: 'Тип', hasDate: true },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Длина, м',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Техническое состояние',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Фотоматериалы',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Техническая документация',
      width: '20rem',
    },
  ],

  // Организация дорожного движения
  'photo-video-violation-fixation': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4420, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4425, name: 'InstallationLocation', code: 'INSTALLATION_LOCATION', type: 'string', title: 'Расположение' },
    { id: 4426, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Направление' },
    { id: 4427, name: 'Type', code: 'TYPE', type: 'violationFixation', title: 'Тип' },
    { id: 4416, name: 'SerialNumber', code: 'SERIAL_NUMBER', type: 'string', title: 'Серийный номер' },
    { id: 4421, name: 'InstallationDate', code: 'INSTALLATION_DATE', type: 'date', title: 'Дата установки' },
    { id: 4424, name: 'InstallationReason', code: 'INSTALLATION_REASON', type: 'string', title: 'Причина установки' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Место установки',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид опоры',
      width: '20rem',
    },
  ],
  'toll-points': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 4133, name: 'Location', code: 'LOCATION', type: 'string', title: 'Местоположение, км+м' },
    { id: 4388, name: 'Direction', code: 'DIRECTION_OF_TRAVEL', type: 'string', title: 'Расположение', hasDate: true },
  ],

  // Мероприятия
  'road-works': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 1972, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 1973, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 1851, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 2321, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    { id: 1657, name: 'TypeOfWorks', code: 'TYPE_OF_WORKS', type: 'string', title: 'Вид работ' },
    { id: 1832, name: 'Deadline', code: 'DEADLINE', type: 'string', title: 'Срок проведения' },
    { id: 0, name: 'SumZnach', code: 'ZNACH', type: 'number', title: 'Предусмотрено, тыс.руб' },
    { id: 0, name: 'FinSource', code: 'ISTOCHNIK_FINANCIROVANIYA', type: 'string', title: 'Источник финансирования' },
    { id: 0, name: 'Project', code: 'PROJECT', type: 'string', title: 'Проект' },
    { id: 2127, name: 'WorkFinish', code: 'WORK_FINISH', type: 'date', title: 'Дата завершения работ' },
  ],
  'road-warranty-parts': [
    { id: 2008, name: 'Map', code: 'MAP', type: 'map', title: '', width: '3rem' },
    { id: 2055, name: 'Start', code: 'START', type: 'string', title: 'Начало участка, км+м' },
    { id: 2056, name: 'Finish', code: 'FINISH', type: 'string', title: 'Конец участка, км+м' },
    { id: 2057, name: 'Length', code: 'LENGTH', type: 'number', title: 'Протяженность, км' },
    { id: 3917, name: 'Square', code: 'SQUARE', type: 'number', title: 'Площадь покрытия проезжей части, кв.м' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Конструктивный элемент',
      width: '20rem',
    },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Наличие гарантийных обязательств',
      width: '20rem',
    },
    { id: 2058, name: 'AssuranceStart', code: 'ASSURANCE_START', type: 'date', title: 'Начало гарантии' },
    { id: 2059, name: 'AssuranceFinish', code: 'ASSURANCE_END', type: 'date', title: 'Окончание гарантии' },
    {
      id: 0,
      name: 'Blank',
      code: 'BLANK',
      type: 'string',
      title: 'Вид работ',
      width: '20rem',
    },
    { id: 0, name: 'Contractor', code: 'CONTRACTOR', type: 'owner', title: 'Подрядчик' },
  ],
};
