import type { CommonInfo } from '../../../features/DetailedView/types';

export const roadResponseFixture: CommonInfo = {
  visibleBlocks: [
    { id: 5, itemCount: 1 },
    { id: 49, itemCount: 3 },
  ],
  directionOfTravel: [
    { id: 1691012, code: '0', text: 'В обе стороны', isNew: false, isDeleted: false },
    { id: 1691011, code: '2', text: 'Обратное направление', isNew: false, isDeleted: false },
    { id: 1691010, code: '1', text: 'Прямое направление', isNew: false, isDeleted: false },
  ],
  hasGeometry: true,
  id: 32197941,
  hash: 'ed5559dce6ebdf3d2aef9402081d1b31',
  isAuthor: false,
  fields: [
    {
      value: { isChanged: false, value: '№ 0000622 Магазин - д № 26' },
      isCustom: false,
      id: 0,
      code: 'FULL_NAME',
      type: 2,
      title: 'Наименование',
      isMultiple: false,
      isRequired: true,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: {
        isChanged: false,
        value: [
          {
            id: 84320268,
            code: '3',
            text: 'АДМИНИСТРАЦИЯ ПАВЛОВСКОГО МУНИЦИПАЛЬНОГО ОКРУГА НИЖЕГОРОДСКОЙ ОБЛАСТИ',
            isNew: false,
            isDeleted: false,
            hash: '1f76c18bee8f0ffb9ccccc2b133fabc8',
          },
        ],
      },
      isCustom: false,
      id: 0,
      code: 'ROAD_OWNER',
      type: 5,
      title: 'Владелец',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: {
        isChanged: false,
        value: [
          { id: 83719, code: '3', text: 'автомобильная дорога местного значения', isNew: false, isDeleted: false },
        ],
      },
      isCustom: false,
      id: 1668,
      code: 'VALUE_OF_THE_ROAD',
      type: 5,
      title: 'Значение автомобильной дороги',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1599,
      code: 'IDENTIFICATION_NUMBER_SECTION',
      type: 2,
      title: 'Идентификационный номер',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1694,
      code: 'UCHET_NUMBER',
      type: 2,
      title: 'Учетный номер',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: {
        isChanged: false,
        value: [
          {
            id: 241543,
            text: 'Нижегородская область',
            isNew: false,
            isDeleted: false,
            hash: 'fb979003809b939c0d637910a362250a',
          },
        ],
      },
      isCustom: false,
      id: 1672,
      code: 'REGION',
      type: 5,
      title: 'Регион',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [{ id: 1466308, text: 'р-н. Павловский', isNew: false, isDeleted: false }] },
      isCustom: false,
      id: 0,
      code: 'DISTRICT',
      type: 5,
      title: 'Район',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 0,
      code: 'CITY',
      type: 5,
      title: 'Город',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [{ id: 1516016, text: 'д. Ново', isNew: false, isDeleted: false }] },
      isCustom: false,
      id: 0,
      code: 'LOCALITY',
      type: 5,
      title: 'Населенный пункт',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 0,
      code: 'PLANNING_STRUCTURE',
      type: 5,
      title: 'Планировочная структура',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 0,
      code: 'INTRACITY_TERRITORY',
      type: 5,
      title: 'Внутригородская территория',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 0,
      code: 'SETTLEMENT_LEVEL',
      type: 5,
      title: 'Уровень городских и сельских поселений',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: 0.34 },
      isCustom: false,
      id: 1666,
      code: 'LENGTH_POPIKETNO',
      type: 3,
      title: 'Протяженность, км',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 3855,
      code: 'ROADWAY_WIDTH',
      type: 3,
      title: 'Ширина проезжей части, м',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 3856,
      code: 'SUBGRADE_WIDTH',
      type: 3,
      title: 'Ширина земляного полотна, м',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1667,
      code: 'SQUARE',
      type: 3,
      title: 'Площадь, кв.м',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1695,
      code: 'BALANCE_STOIM',
      type: 3,
      title: 'Балансовая стоимость, тыс. руб.',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1697,
      code: 'OSTATOK',
      type: 3,
      title: 'Остаточная стоимость, тыс. руб.',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 2175,
      code: 'RANKS',
      type: 3,
      title: 'Число полос движения, шт.',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 1831,
      code: 'ROAD_CATEGORY',
      type: 5,
      title: 'Категория',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: {
        isChanged: false,
        value: [
          {
            id: 1643514,
            code: '7',
            text: 'Улицы и дороги местного значения - улицы в зонах жилой застройки',
            isNew: false,
            isDeleted: false,
          },
        ],
      },
      isCustom: false,
      id: 2275,
      code: 'CATEGORY_SNIP',
      type: 5,
      title: 'Категория по СНиП 2.07.01-89',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1696,
      code: 'DATA_EXPL',
      type: 4,
      title: 'Дата ввода в эксплуатацию',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: {
        isChanged: false,
        value: [{ id: 1643483, code: '8', text: 'Грунтовые', isNew: false, isDeleted: false }],
      },
      isCustom: false,
      id: 2201,
      code: 'COATING',
      type: 5,
      title: 'Виды покрытия',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 2170,
      code: 'CLASS_OF_ROAD',
      type: 5,
      title: 'Класс',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 2171,
      code: 'TOP_SPEED',
      type: 3,
      title: 'Максимальная скорость, км/ч',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 2050,
      code: 'INTERNATIONAL',
      type: 5,
      title: 'Международный маршрут',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 2174,
      code: 'THROUGHPUT',
      type: 3,
      title: 'Макс.проектная пропускная способность, авт/сут',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 3858,
      code: 'TRAFFIC_INTENSITY',
      type: 3,
      title: 'Интенсивность движения, авт/сут',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 3857,
      code: 'CLIMATIC_ZONE',
      type: 5,
      title: 'Дорожно-климатическая зона',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: [] },
      isCustom: false,
      id: 4092,
      code: 'HUMIDIFICATION_COND',
      type: 5,
      title: 'Тип местности по условиям увлажнения',
      isMultiple: true,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 1829,
      code: 'LOCATION_START',
      type: 2,
      title: 'Начало дороги',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: true },
      isCustom: false,
      id: 2120,
      code: 'IS_CHECKED',
      type: 6,
      title: 'Информация проверена',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: {
        isChanged: false,
        value: [
          {
            id: 16570548,
            text: 'Крюков Алексей Александрович',
            isNew: false,
            isDeleted: false,
            hash: 'fc3880480cc607ca17d57576137f1e65',
          },
        ],
      },
      isCustom: false,
      id: 0,
      code: 'CONFIRM_USER',
      type: 5,
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: '01.07.2021' },
      isCustom: false,
      id: 0,
      code: 'DATA_CONFIRMATION',
      type: 4,
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: '11:23:51' },
      isCustom: false,
      id: 0,
      code: 'TIME_CONFIRMATION',
      type: 2,
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false },
      isCustom: false,
      id: 4187,
      code: 'NORM_PERCENTAGE',
      type: 3,
      title: 'Нормативное состояние, %',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
    {
      value: { isChanged: false, value: false },
      isCustom: false,
      id: 4412,
      code: 'CORE_NETWORK',
      type: 6,
      title: 'Входит в опорную сеть',
      isMultiple: false,
      isRequired: false,
      isReadonly: false,
      isEntity: false,
    },
  ],
};

export const blankStoreJSON =
  '{"accessMatrixStore":{"accessMatrix":{"page_account__block_projects_lists_of_highways":false,"page_account__block_road_activity":false,"page_account__block_road_activity__roads":false,"page_account__block_operational_management":false,"page_account__block_operational_management__protocols":false,"page_account__block_project_activity":false,"page_account__block_analitycs":false,"page_account__block_notifications":false,"menu_desktop":false,"menu_notifications":false,"menu_account_page":false,"menu_newsletter":false,"menu_map":true,"menu_roads":true,"menu_bridges":false,"menu_events":false,"menu_accidents":true,"menu_citizen_messages":false,"menu_documents":false,"menu_protocols":false,"menu_projects":false,"menu_tasks":false,"menu_contacts":false,"menu_open_data":false,"menu_developers":false,"menu_contracts":false,"menu_procurement_plans":false,"menu_plan_schedules":false,"menu_purchase_notices":false,"menu_citizen_appeals":false,"menu_nsi":false,"menu_data_import":false,"menu_registration_applications":false,"menu_road_diagnostics":false,"menu_user_accounts":false,"menu_cubes":false,"menu_indicators":false,"menu_analytics":false,"menu_region_passport":false,"menu_reporting_form_3_autodor":false,"menu_reporting_form_7_autodor":false,"menu_reporting_form_1_dg":false,"menu_reporting_form_2_dg":false,"menu_reporting_form_1_fd":false,"menu_reporting_form_1_km_price":false,"menu_reporting_form_monitoring":false,"roads__export":false,"roads__show_on_map":false,"roads__reports":false,"roads_card__export_pdf":false,"roads_card__edit":false,"roads_card__print":false,"roads_card__show_on_map":false,"roads_card__history":false,"roads_card__relations":false,"roads_card__checked_status":false,"traffic_accidents__export":false,"traffic_accidents__form_aou":false,"traffic_accidents__show_on_map":false,"traffic_accidents__accept_aop":false,"traffic_accidents__reject_aop":false,"traffic_accidents_card__export":false,"traffic_accidents_card__print":false,"traffic_accidents_card__show_on_map":false,"traffic_accidents_card__history":false,"events__export":false,"events__create":false,"events__show_on_map":false,"events_card__print":false,"events_card__export":false,"events_card__edit":false,"events_card__favorite":false,"events_card__export_pdf":false,"events_card__show_on_map":false,"events_card__checked_status":false,"events_card__history":false,"bridges__export":false,"bridges__show_on_map":false,"bridges_card__print":false,"bridges_card__edit":false,"bridges_card__show_on_map":false,"bridges_card__checked_status":false,"bridges_card__history":false,"procurement_plans__export":false,"procurement_plans_card__print":false,"procurement_plans_card__export":false,"procurement_plans_card__edit":false,"procurement_plans_card__relations":false,"procurement_plans_card__history":false,"projects__export":false,"projects__create":false,"projects_card__print":false,"projects_card__edit":false,"projects_card__export":false,"projects_card__create_copy":false,"tasks__export":false,"tasks__create":false,"tasks__reports":false,"tasks__copy":false,"tasks__delete":false,"tasks_card__edit":false,"tasks_card__print":false,"tasks_card__favorite":false,"tasks_card__delegate":false,"tasks_card__get_to_work":false,"tasks_card__interrupt":false,"tasks_card__request_for_postponement":false,"tasks_card__resume":false,"tasks_card__cancel_postponement":false,"tasks_card__reply_for_postponement":false,"tasks_card__complete":false,"tasks_card__accept":false,"tasks_card__reject":false,"documents__export":false,"documents__create":false,"documents_card__edit":false,"documents_card__print":false,"documents_card__export":false,"documents_card__favorite":false,"documents_card__acquaint":false,"documents_card__start-approve":false,"documents_card__restart-approve":false,"documents_card__reset-approve":false,"documents_card__interrupt-approve":false,"documents_card__reject-approve":false,"documents_card__accept-approve":false,"documents_card__create-approve-sub-step":false,"plan_schedules__export":false,"plan_schedules_card__export":false,"plan_schedules_card__print":false,"plan_schedules_card__edit":false,"plan_schedules_card__relations":false,"plan_schedules_card__history":false,"purch_notices__export":false,"purch_notices_card__export":false,"purch_notices_card__print":false,"purch_notices_card__edit":false,"purch_notices_card__relations":false,"purch_notices_card__history":false,"contracts__export":false,"contracts__create":false,"contracts_card__export":false,"contracts_card__print":false,"contracts_card__relations":false,"contracts_card__edit":false,"contracts_card__checked_status":false,"contracts_card__history":false,"nsi__section-data":false,"nsi__section-setup":false,"nsi__export":false,"nsi__import":false,"nsi__edit":false,"data_import__section-data":false,"data_import__section-configurator":false,"protocols__export":false,"protocols__create":false,"protocols__reports":false,"protocols_card__print":false,"protocols_card__edit":false,"protocols_card__common_info__edit":false,"protocols_card__files__edit":false,"protocols_card__participants__edit":false,"protocols_card__resolutions__edit":false,"protocols_card__export":false,"messages__export":false,"messages__deadline_settings":false,"messages_card__print":false,"messages_card__show_on_map":false,"messages_card__export":false,"messages_card__status_history":false,"messages_card__change_status":false,"messages_card__history":false,"users__export":false,"users__create":false,"users__groups":false,"user_groups__add_group":false,"user_groups__form_by_rules":false,"user_groups__edit":false,"user_groups__favorite":false,"users_card__print":false,"users_card__edit":false,"user_groups_card__print":false,"map__show_as_table":false,"map__print":false,"map__add":false,"map__relations":false,"map__edit":false,"map__to_card":false,"road_on_balance_card__export_pdf":false,"road_on_balance_card__edit":false,"road_on_balance_card__print":false,"road_on_balance_card__show_on_map":false,"road_on_balance_card__checked_status":false,"road_on_balance_card__history":false,"user_accounts__export":false,"user_accounts_card__edit":false,"user_accounts_card__print":false,"user_accounts_card__history":false,"user_accounts_card__actions__block":false,"user_accounts_card__actions__refresh_password":false,"user_accounts_card__actions__register":false,"user_accounts_card__actions__set_as_clarified":false,"user_accounts_card__actions__set_as_duplicate":false,"user_accounts_card__actions__set_as_on_clarification":false,"user_accounts_card__actions__unblock":false,"user_accounts_card__actions__refresh_original_password":false,"reporting_form_3_autodor__organization_report_list":false,"reporting_form_3_autodor__subject_rf_report_list":false,"reporting_form_3_autodor__summary":false,"reporting_form_3_autodor__confirm_doc_edit":false,"reporting_form_3_autodor__edit":false,"reporting_form_3_autodor__import":false,"reporting_form_3_autodor__approvement__send":false,"reporting_form_3_autodor__approvement__start_new":false,"reporting_form_3_autodor__approvement__approve":false,"reporting_form_3_autodor__approvement__reject":false,"reporting_form_3_autodor__auto_calc":false,"reporting_form_7_autodor__summary":false,"reporting_form_7_autodor__confirm_doc_edit":false,"reporting_form_7_autodor__edit":false,"reporting_form_7_autodor__import":false,"reporting_form_7_autodor__approvement__send":false,"reporting_form_7_autodor__approvement__start_new":false,"reporting_form_7_autodor__approvement__approve":false,"reporting_form_7_autodor__approvement__reject":false,"reporting_form_7_autodor__auto_calc":false,"reporting_form_1_dg__organization_report_list":false,"reporting_form_1_dg__subject_rf_report_list":false,"reporting_form_1_dg__summary":false,"reporting_form_1_dg__confirm_doc_edit":false,"reporting_form_1_dg__edit":false,"reporting_form_1_dg__import":false,"reporting_form_1_dg__approvement__send":false,"reporting_form_1_dg__approvement__start_new":false,"reporting_form_1_dg__approvement__approve":false,"reporting_form_1_dg__approvement__reject":false,"reporting_form_1_dg__auto_calc":false,"reporting_form_2_dg__organization_report_list":false,"reporting_form_2_dg__subject_rf_report_list":false,"reporting_form_2_dg__summary":false,"reporting_form_2_dg__confirm_doc_edit":false,"reporting_form_2_dg__edit":false,"reporting_form_2_dg__import":false,"reporting_form_2_dg__approvement__send":false,"reporting_form_2_dg__approvement__start_new":false,"reporting_form_2_dg__approvement__approve":false,"reporting_form_2_dg__approvement__reject":false,"reporting_form_2_dg__auto_calc":false,"reporting_form_1_fd__organization_report_list":false,"reporting_form_1_fd__subject_rf_report_list":false,"reporting_form_1_fd__summary":false,"reporting_form_1_fd__confirm_doc_edit":false,"reporting_form_1_fd__edit":false,"reporting_form_1_fd__import":false,"reporting_form_1_fd__approvement__send":false,"reporting_form_1_fd__approvement__start_new":false,"reporting_form_1_fd__approvement__approve":false,"reporting_form_1_fd__approvement__reject":false,"reporting_form_1_fd__auto_calc":false,"reporting_form_1_fd__laws_edit":false,"reporting_form_monitoring__summary":false,"reporting_form_monitoring__confirm_doc_edit":false,"reporting_form_monitoring__edit":false,"reporting_form_monitoring__import":false,"reporting_form_monitoring__approvement__send":false,"reporting_form_monitoring__approvement__start_new":false,"reporting_form_monitoring__approvement__approve":false,"reporting_form_monitoring__approvement__reject":false,"reporting_form_monitoring__auto_calc":false,"reporting_form_monitoring__laws_edit":false,"reporting_form_1_km_price__organization_report_list":false,"reporting_form_1_km_price__subject_rf_report_list":false,"reporting_form_1_km_price__summary":false,"reporting_form_1_km_price__confirm_doc_edit":false,"reporting_form_1_km_price__edit":false,"reporting_form_1_km_price__import":false,"reporting_form_1_km_price__approvement__send":false,"reporting_form_1_km_price__approvement__start_new":false,"reporting_form_1_km_price__approvement__approve":false,"reporting_form_1_km_price__approvement__reject":false,"reporting_form_1_km_price__auto_calc":false,"page_account__block_statistics":false,"page_account__block_statistics__form_3_autodor":false,"page_account__block_statistics__form_3_autodor__part_organizations":false,"page_account__block_statistics__form_3_autodor__part_regions":false,"page_account__block_statistics__form_7_autodor":false,"page_account__block_statistics__form_7_autodor__part_organizations":false,"page_account__block_statistics__form_1_dg":false,"page_account__block_statistics__form_1_dg__part_organizations":false,"page_account__block_statistics__form_1_dg__part_regions":false,"page_account__block_statistics__form_2_dg":false,"page_account__block_statistics__form_2_dg__part_organizations":false,"page_account__block_statistics__form_2_dg__part_regions":false,"page_account__block_statistics__form_1_fd":false,"page_account__block_statistics__form_1_fd__part_organizations":false,"page_account__block_statistics__form_1_fd__part_regions":false,"page_account__block_statistics__form_1_km_price":false,"page_account__block_statistics__form_1_km_price__part_organizations":false,"page_account__block_statistics__form_1_km_price__part_regions":false,"page_account__block_statistics__form_monitoring":false,"page_account__block_statistics__form_monitoring__part_regions":false},"fetchState":"pending"},"id":null,"hash":null,"isAuthor":false,"hasGeometry":false,"navigationTemplate":{"roadOwners":{"id":"roadOwners","name":"Собственники, владельцы дороги и эксплуатирующие организации","blocks":[{"id":3,"name":"Собственник, владелец (балансодержатель)","endpoint":"road-owners","saveEndpoint":"roadOwners"},{"id":4,"name":"Эксплуатирующая организация","endpoint":"operating-organizations","saveEndpoint":"operatingOrganizations"}]},"regulatoryDocuments":{"id":"regulatoryDocuments","name":"Нормативно-правовые документы","blocks":[{"id":5,"name":"Нормативно-правовые документы","endpoint":"regulations"},{"id":100,"name":"Выписки","endpoint":"excerpts"},{"id":6,"name":"Поручения","endpoint":"instructions"}]},"additionalInfo":{"id":"additionalInfo","name":"Дополнительная информация об участках","blocks":[{"id":110,"name":"Участки, входящие в опорную сеть","endpoint":"backbone-network","saveEndpoint":"backboneNetwork"},{"id":7,"name":"Дата ввода в эксплуатацию","endpoint":"start-exploitation","saveEndpoint":"startExploitations"},{"id":8,"name":"Участки, используемые на платной основе","endpoint":"paid-section-of-the-road","saveEndpoint":"paidSections"},{"id":26,"name":"Участки дороги, работающие в режиме перегрузки","endpoint":"overloaded-roads","saveEndpoint":"overloadedRoads"},{"id":24,"name":"Места концентрации дорожно-транспортных происшествий (аварийно-опасные участки)","endpoint":"dangerous-sections","saveEndpoint":"dangerousSections"},{"id":20,"name":"Участки повышенной трудности содержания","endpoint":"increased-maintenance-complexity","saveEndpoint":"increasedMaintenanceComplexities"}]},"location":{"id":"location","name":"Местоположение","blocks":[{"id":44,"name":"Прохождение дороги по территории субъектов Российской Федерации","endpoint":"cross-subjects","saveEndpoint":"crossSubjects"},{"id":45,"name":"Прохождение дороги по территории городских агломераций","endpoint":"agglomerations","saveEndpoint":"agglomerations"},{"id":46,"name":"Дорожно-климатическая зона","endpoint":"climatic-zones","saveEndpoint":"climaticZones"},{"id":47,"name":"Тип местности по условиям увлажнения","endpoint":"terrain-types","saveEndpoint":"terrainTypes"}]},"generalTechnicalData":{"id":"generalTechnicalData","name":"Общие технические данные","blocks":[{"id":17,"name":"Максимальная разрешенная скорость","endpoint":"max-speeds","saveEndpoint":"maximumSpeeds"},{"id":16,"name":"Нагрузка на ось","endpoint":"axle-loads","saveEndpoint":"axleLoads"},{"id":18,"name":"Пропускная способность","endpoint":"throughputs","saveEndpoint":"throughputs"},{"id":19,"name":"Среднесуточная интенсивность и состав движения","endpoint":"traffic-intensities","saveEndpoint":"trafficIntensities"},{"id":21,"name":"Ограничения габаритных и весовых параметров транспортных средств","endpoint":"oversized-cargo-limitations","saveEndpoint":"oversizedCargoLimitations"}]},"roadwayAndSubgrade":{"id":"roadwayAndSubgrade","name":"Проезжая часть и земляное полотно","blocks":[{"id":10,"name":"Категория","endpoint":"categories","saveEndpoint":"categories"},{"id":15,"name":"Класс","endpoint":"road-class","saveEndpoint":"roadClasses"},{"id":13,"name":"Число полос движения","endpoint":"number-of-lanes","saveEndpoint":"numberOfLanes"},{"id":11,"name":"Ширина основной проезжей части дороги","endpoint":"roadway-width","saveEndpoint":"roadwayWidths"},{"id":12,"name":"Земляное полотно","endpoint":"earthen-canvas-width","saveEndpoint":"earthenCanvasWidths"},{"id":14,"name":"Тип дорожной одежды и вид покрытия","endpoint":"type-of-coatings","saveEndpoint":"typeOfCoatings"}]},"intersections":{"id":"intersections","name":"Пересечения и примыкания","blocks":[{"id":48,"name":"Пересечения с коммуникациями","endpoint":"communication-intersections","saveEndpoint":"communicationIntersections"},{"id":49,"name":"Пересечения и примыкания с автомобильными дорогами","endpoint":"road-intersections","saveEndpoint":"roadIntersections"},{"id":50,"name":"Пересечения с железными дорогами","endpoint":"railway-intersections","saveEndpoint":"railwayIntersections"},{"id":2,"name":"Участки дороги","endpoint":"road-parts","saveEndpoint":"roadParts"}]},"roadSafety":{"id":"roadSafety","name":"Элементы обустройства","blocks":[{"id":31,"name":"Светофоры","endpoint":"traffic-lights","saveEndpoint":"trafficLights"},{"id":30,"name":"Освещение","endpoint":"lightning","saveEndpoint":"lightnings"},{"id":32,"name":"Остановки общественного транспорта","endpoint":"road-stops","saveEndpoint":"roadStops"},{"id":38,"name":"Тротуары, пешеходные и велосипедные дорожки","endpoint":"sidewalks","saveEndpoint":"sidewalks"},{"id":41,"name":"Шумозащитные сооружения","endpoint":"soundproofing-buildings","saveEndpoint":"soundProofingBuildings"},{"id":52,"name":"Дорожные ограждения","endpoint":"barriers","saveEndpoint":"barriers"},{"id":43,"name":"Километровые знаки","endpoint":"kilometer-pillars","saveEndpoint":"kilometerPillars"},{"id":91,"name":"Пункты весогабаритного контроля","endpoint":"weight-control-points","saveEndpoint":"weightControlPoints"},{"id":92,"name":"Фотовидеофиксация нарушений","endpoint":"photo-video-violation-fixation","saveEndpoint":"photoVideoViolationFixations"},{"id":90,"name":"Пункты оплаты проезда","endpoint":"toll-points","saveEndpoint":"tollPoints"}]},"serviceFacilities":{"id":"serviceFacilities","name":"Объекты дорожного сервиса","blocks":[{"id":35,"name":"Автозаправочные станции","endpoint":"gas-stations","saveEndpoint":"gasStations"},{"id":36,"name":"Станции технического обслуживания","endpoint":"service-stations","saveEndpoint":"serviceStations"},{"id":37,"name":"Площадки отдыха, стоянки","endpoint":"platforms","saveEndpoint":"platforms"},{"id":34,"name":"Станции, вокзалы","endpoint":"stations","saveEndpoint":"stations"},{"id":39,"name":"Гостиницы, мотели, кемпинги","endpoint":"vacation-spots","saveEndpoint":"vacationSpots"},{"id":51,"name":"Пункты медицинской помощи","endpoint":"medical-institutions","saveEndpoint":"medicalInstitutions"},{"id":40,"name":"Многофункциональные зоны","endpoint":"multifunctional-zones","saveEndpoint":"multifunctionalZones"}]},"regulatoryStatus":{"id":"regulatoryStatus","name":"Нормативное / ненормативное состояние","blocks":[{"id":25,"name":"Участки, соответствующие нормативным требованиям","endpoint":"regulatory-statuses","saveEndpoint":"regulatoryStatuses"}]},"technicalCondition":{"id":"technicalCondition","name":"Оценка технического состояния (результаты)","blocks":[{"id":27,"name":"Диагностика","endpoint":"diagnostics","saveEndpoint":"diagnostics"}]},"artificialConstructionsBlocks":{"id":"artificialConstructionsBlocks","name":"Искусственные сооружения","blocks":[{"id":22,"name":"Мостовые сооружения","endpoint":"bridge-construction","saveEndpoint":"bridgeConstructions"},{"id":23,"name":"Трубы дорожные водопропускные","endpoint":"pipes","saveEndpoint":"pipes"},{"id":42,"name":"Локальные очистные сооружения","endpoint":"local-treatment-buildings","saveEndpoint":"localTreatmentBuildings"},{"id":33,"name":"Пешеходные переходы","endpoint":"pedestrian-crossings","saveEndpoint":"pedestrianCrossings"}]},"roadWorks":{"id":"roadWorks","name":"Мероприятия","blocks":[{"id":28,"name":"Участки проведения работ","endpoint":"road-works","saveEndpoint":"roadWorks"},{"id":29,"name":"Участки дороги на гарантии","endpoint":"road-warranty-parts","saveEndpoint":"roadWarrantyParts"}]}},"meta":{"road-owners":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2008,"name":"Start","code":"START","type":"roadStartSectionLink","title":"Начало участка, км+м"},{"id":2009,"name":"Finish","code":"FINISH","type":"roadFinishSectionLink","title":"Конец участка, км+м"},{"id":2010,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":2420,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":2421,"name":"BalanceStoim","code":"BALANCE_STOIM","type":"number","title":"Балансовая стоимость, тыс. руб."},{"id":2422,"name":"Ostatok","code":"OSTATOK","type":"number","title":"Остаточная стоимость, тыс. руб."},{"id":201,"name":"Owner","code":"OWNER","type":"owner","externalKey":"name","title":"Полное наименование юридического лица / ФИО физического лица","width":"45rem","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид документа-основания возникновения вещного права","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Основные реквизиты документа-основания","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Наименование вещного права","width":"20rem"}],"operating-organizations":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2245,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2244,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2246,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3860,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":0,"name":"Name","code":"FULL_NAME","type":"owner","externalKey":"name","title":"Полное наименование юридического лица","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид документа-основания возникновения вещного права","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Основные реквизиты документа-основания","width":"20rem"}],"regulations":[{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"№ п/п"},{"id":0,"name":"Name","code":"FULL_NAME","type":"string","title":"Наименование"},{"id":3165,"name":"RegNumber","code":"REG_NUMBER","type":"string","title":"№"},{"id":3156,"name":"RegDate","code":"REG_DATE","type":"date","title":"Дата"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Уровень","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Статус"},{"id":3161,"name":"Description","code":"DESCRIPTION","type":"string","title":"Орган системы управления"},{"id":0,"name":"File","code":"FILE","type":"file","title":"Документ-основание"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата размещения сведений","width":"20rem"}],"backbone-network":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":5519,"name":"Start","code":"START","type":"roadStartBackboneNetwork","title":"Начало участка, км+м"},{"id":5517,"name":"Finish","code":"FINISH","type":"roadFinishBackboneNetwork","title":"Конец участка, км+м"},{"id":5518,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Категория критерия","width":"20rem"},{"id":5516,"name":"Criterion","code":"CRITERION","type":"string","title":"Критерии опорной сети","hasDate":true},{"id":5514,"name":"Itr","code":"ITR","type":"string","title":"МТМ"}],"start-exploitation":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2268,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2267,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2269,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":2265,"name":"Date","code":"DATA_EXPL","type":"date","title":"Дата ввода в эксплуатацию"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид работ","width":"20rem"}],"paid-section-of-the-road":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2051,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2052,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2060,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Площадь покрытия проезжей части, кв.м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Местоположение пунктов взимания платы (ПВП)","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"},{"id":0,"name":"Tariff","code":"OTHER","type":"string","title":"Тариф","hasDate":true}],"overloaded-roads":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":1887,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":1888,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":1889,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Площадь покрытия проезжей части, кв.м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"}],"dangerous-sections":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":1885,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":1886,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":1846,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Площадь покрытия проезжей части, кв.м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"},{"id":1845,"name":"RegistrationDate","code":"REGISTRATION_DATE","type":"string","title":"Дата регистрации"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата снятия с регистрации","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Наличие в ПКРТИ","titleHint":"Наличие в программе комплексного развития транспортной инфраструктуры","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Недостатки транспортно-эксплуатационного состояния в местах совершения ДТП по карточкам учета по ДУ"},{"id":1646,"name":"Description","code":"DESCRIPTION","type":"string","title":"Причина возникновения"},{"id":1890,"name":"DtpType","code":"DTP_TYPE","type":"string","title":"Вид ДТП"},{"id":0,"name":"CountAccident","code":"COUNT_ACCIDENT","type":"number","title":"Количество ДТП"},{"id":0,"name":"Injured","code":"INJURED","type":"number","title":"Количество пострадавших","children":[{"id":0,"name":"Wounded","code":"WOUNDED","type":"number","title":"Ранено"},{"id":0,"name":"Dead","code":"DEAD","type":"number","title":"Погибло"}]},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата размещения сведений","width":"20rem"}],"increased-maintenance-complexity":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3901,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3902,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":3903,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3904,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":4094,"name":"NatureOfSites","code":"NATURE_OF_SITES","type":"string","title":"Характер участков","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"}],"cross-subjects":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2028,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2029,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2030,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3915,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":123445555,"name":"Subject","code":"SUBJECT","type":"region","title":"Субъект РФ","hasDate":true}],"agglomerations":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2032,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2033,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2034,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3914,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":123,"name":"Name","code":"FULL_NAME","type":"agglomeration","title":"Городская агломерация","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"},{"id":5528,"name":"TypeLastWork","code":"TYPE_LAST_WORK","type":"string","title":"Вид последних работ"},{"id":5526,"name":"LastDateWork","code":"LAST_DATE_WORK","type":"string","title":"Дата последнего проведения работ"}],"climatic-zones":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":0,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":0,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":0,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":4090,"name":"Name","code":"CLIMATIC_ZONE","type":"string","title":"Дорожно-климатическая зона","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"}],"terrain-types":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4077,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":4078,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":4079,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":4089,"name":"Name","code":"HUMIDIFICATION_COND","type":"string","title":"Тип местности по условиям увлажнения","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Субъект РФ"}],"max-speeds":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2280,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2279,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2282,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3478,"name":"MaxSpeed","code":"VALUE","type":"number","title":"Максимальная разрешенная скорость, км/ч","hasDate":true}],"axle-loads":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":0,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":0,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":0,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3673,"name":"Os","code":"OS","type":"string","title":"Расчётная нагрузка на ось, Мпа","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Максимальный вес на двойную ось транспортного средства","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Максимальный вес на тройную ось транспортного средства","width":"20rem"},{"id":0,"name":"File","code":"FILE","type":"file","title":"Документы, подтверждающие значение расчетной нагрузки на ось","width":"20rem"}],"throughputs":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2273,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2272,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2276,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3478,"name":"MaxBandwidth","code":"VALUE","type":"number","title":"Пропускная способность, авт/сут","hasDate":true,"width":"15rem"}],"traffic-intensities":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3880,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3878,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":3882,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3879,"name":"AccountingPoint","code":"ACCOUNTING_POINT","type":"string","title":"Местоположение учетного пункта, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Легковые","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Грузовые легкие","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Грузовые средние","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Значение"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"В т. ч. автопоезда"}]},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Грузовые тяжелые","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Значение"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"В т. ч. автопоезда"}]},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Грузовые сверхтяжелые","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Значение"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"В т. ч. автопоезда"}]},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Автобусы","width":"20rem"},{"id":3478,"name":"TrafficIntensity","code":"VALUE","type":"number","title":"Среднесуточная интенсивность движения, авт/сут","hasDate":true}],"oversized-cargo-limitations":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4069,"name":"Start","code":"START","type":"string","title":"Начало участка"},{"id":4070,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка"},{"id":4071,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":4083,"name":"NatureOfSites","code":"NATURE_OF_SITES","type":"string","title":"Характер ограничения","hasDate":true},{"id":0,"name":"Sizings","code":"SIZINGS","type":"number","title":"Габарит проезда","width":"35rem","children":[{"id":4186,"name":"Size","code":"SIZE","type":"number","title":"По ширине, м"},{"id":4444,"name":"Height","code":"HEIGHT_SIZE","type":"number","title":"По высоте, м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"По длине, м"},{"id":4445,"name":"Weight","code":"SIZE_SCALES","type":"number","title":"По весу, т"}]},{"id":0,"name":"Other","code":"OTHER","type":"string","title":"Реквизиты нормативно-правового документа"}],"categories":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2016,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2017,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2018,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":2307,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":2022,"name":"Name","code":"CATEGORY","type":"string","title":"Техническая категория","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Рельеф местности","width":"20rem"},{"id":3883,"name":"CategorySp","code":"CATEGORY_SP","type":"string","title":"Категория дороги (группа улицы) согласно СП 42.13330-2016"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расчетная скорость движения, км/ч","width":"20rem"}],"road-class":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2226,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2227,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2224,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3872,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м","width":"17rem"},{"id":2222,"name":"RoadClass","code":"CLASS_OF_ROAD","type":"string","title":"Класс","hasDate":true,"width":"13rem"}],"number-of-lanes":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2207,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2208,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2209,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3871,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":3478,"name":"Count","code":"VALUE","type":"number","title":"Число полос движения на участке","hasDate":true}],"roadway-width":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3861,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3862,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":3863,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3864,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":3478,"name":"Width","code":"VALUE","type":"number","title":"Ширина, м","hasDate":true}],"earthen-canvas-width":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3866,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3867,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":3868,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3478,"name":"Width","code":"VALUE","type":"number","title":"Ширина земляного полотна поверху, м","hasDate":true},{"id":3870,"name":"CoverageArea","code":"COVERAGE_AREA","type":"number","title":"Площадь земляного полотна поверху, кв.м"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Высота насыпи/глубина выемки","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"справа, м"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"слева, м"}]},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Заложение откосов","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"справа"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"слева"}]},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Грунт земляного полотна","width":"20rem"}],"type-of-coatings":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2212,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2213,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2214,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":2240,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Тип дорожной одежды ","width":"20rem"},{"id":2215,"name":"Coating","code":"COATING","type":"string","title":"Вид покрытия","hasDate":true,"width":"13rem"}],"communication-intersections":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4036,"name":"Intersection","code":"INTERSECTION","type":"string","title":"Место пересечения, км+м"},{"id":2294,"name":"Type","code":"TYP_COM","type":"string","title":"Вид коммуникаций"},{"id":4037,"name":"Size","code":"SIZE","type":"number","title":"Габарит проезда по ширине, м"},{"id":4329,"name":"HeightSize","code":"HEIGHT_SIZE","type":"number","title":"Габарит проезда по высоте, м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата размещения сведений","width":"20rem"}],"road-intersections":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4082,"name":"Intersection","code":"INTERSECTION","type":"string","title":"Место пересечения, км+м"},{"id":0,"name":"Name","code":"FULL_NAME","type":"roadLink","title":"Пересекаемая/примыкающая автомобильная дорога"},{"id":2219,"name":"LevelsCount","code":"NUMBER_OF_LEVELS","type":"number","title":"Количество уровней"},{"id":4081,"name":"Size","code":"SIZE","type":"number","title":"Габарит проезда по ширине, м"},{"id":4330,"name":"HeightSize","code":"HEIGHT_SIZE","type":"number","title":"Габарит проезда по высоте, м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата размещения сведений","width":"20rem"}],"railway-intersections":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Место пересечения, км+м","width":"20rem"},{"id":5376,"name":"Type","code":"TYPE","type":"string","title":"Уровень пересечения"},{"id":4015,"name":"Size","code":"SIZE","type":"number","title":"Габарит проезда по ширине, м"},{"id":4331,"name":"HeightSize","code":"HEIGHT_SIZE","type":"number","title":"Габарит проезда по высоте, м"},{"id":4014,"name":"NumberOfPaths","code":"NUMBER_OF_PATHS","type":"number","title":"Количество путей, шт"},{"id":4045,"name":"Name","code":"FULL_NAME","type":"string","title":"Наименование ж/д направления"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата размещения сведений","width":"20rem"}],"road-parts":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3911,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3912,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2367,"name":"Length","code":"LENGTH_POPIKETNO","type":"number","title":"Протяженность, км"},{"id":2368,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":2359,"name":"Type","code":"ROAD_LOCATION_TYPE","type":"string","title":"Тип участка","hasDate":true}],"traffic-lights":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3973,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение"},{"id":4045,"name":"InstallationLocation","code":"INSTALLATION_LOCATION","type":"string","title":"Место установки","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Транспортные светофоры","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"тип"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"количество, шт"}]},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"Пешеходные светофоры","width":"20rem","children":[{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"тип"},{"id":0,"name":"Blank","code":"BLANK","type":"number","title":"количество, шт"}]},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расположение","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид опоры","width":"20rem"}],"lightning":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2012,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2013,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":0,"name":"PropCount","code":"VALUE","type":"number","title":"Количество опор, шт."},{"id":2024,"name":"DefectPropCount","code":"DEFECT_PROP_COUNT","type":"number","title":"Количество опор с дефектами, шт."},{"id":2025,"name":"LightCount","code":"LIGHT_COUNT","type":"number","title":"Количество светильников, шт.","hasDate":true}],"road-stops":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3974,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение"},{"id":4138,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Name","code":"FULL_NAME","type":"string","title":"Наименование"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Наличие элементов","width":"20rem"},{"id":4137,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true}],"sidewalks":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3979,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":0,"name":"Finish","code":"Finish","type":"string","title":"Конец участка, км+м"},{"id":3982,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3983,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия, кв.м"},{"id":4144,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":4049,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true},{"id":3984,"name":"Width","code":"WIDTH","type":"number","title":"Ширина, м"}],"soundproofing-buildings":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3988,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3989,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":3991,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":4147,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":4051,"name":"Type","code":"TYPE","type":"string","title":"Вид","hasDate":true},{"id":3992,"name":"Height","code":"HEIGHT","type":"number","title":"Высота сооружения, м"}],"barriers":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4332,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":4333,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":4334,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расположение","width":"20rem"},{"id":4339,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Материал","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Световозвращатель","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Высота, м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дефекты","width":"20rem"}],"kilometer-pillars":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4030,"name":"Number","code":"POST_NUMBER","type":"number","title":"№ столба"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние до следующего километрового знака, м","width":"20rem"},{"id":4034,"name":"Latitude","code":"LATITUDE","type":"string","title":"Широта"},{"id":4035,"name":"Longtitude","code":"LONGITUDE","type":"string","title":"Долгота","hasDate":true}],"gas-stations":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3995,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4141,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Границы размещения","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние от внешней границы обочины, м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Тип топлива ","width":"20rem"},{"id":4053,"name":"Type","code":"TYPE","type":"string","title":"Тип"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Количество заправочных колонок, шт","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Площадь, кв. м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Принадлежность","width":"20rem"},{"id":0,"name":"Organization","code":"ORGANIZATION","type":"owner","title":"Организация","hasDate":true}],"service-stations":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3997,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4142,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Границы размещения ","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние от внешней границы обочины, м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Количество постов на СТО, шт","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Принадлежность","width":"20rem"}],"platforms":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3977,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4143,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Границы размещения","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние от внешней границы обочины, м","width":"20rem"},{"id":4047,"name":"Type","code":"TYPE","type":"string","title":"Тип"},{"id":4048,"name":"Coating","code":"COATING","type":"string","title":"Вид покрытия","width":"13rem","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Количество машиномест","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Оборудование","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Принадлежность","width":"20rem"}],"stations":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3993,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4140,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":4052,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true}],"vacation-spots":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3999,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4145,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Границы размещения","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние от внешней границы обочины, м","width":"20rem"},{"id":4055,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Наименование","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Принадлежность","width":"20rem"},{"id":5383,"name":"Url","code":"URL","type":"string","title":"Интернет-сайт"}],"weight-control-points":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4381,"name":"Location","code":"LOCATIONN","type":"string","title":"Местоположение, км+м"},{"id":4377,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Status","code":"STATUS","type":"string","title":"Статус"},{"id":2754,"name":"Type","code":"POST_TYPE","type":"string","title":"Тип ПВГК"},{"id":2751,"name":"Model","code":"WEIGHT","type":"number","title":"Марка и модель весов","hasDate":true},{"id":4378,"name":"AxleLoad","code":"OS","type":"string","title":"Нагрузка на ось, тонн/ось"},{"id":0,"name":"BalanceHolder","code":"BalanceHolder","type":"owner","title":"Балансодержатель"},{"id":0,"name":"OperatingOrganization","code":"OperatingOrganization","type":"owner","title":"Эксплуатирующая организация"}],"medical-institutions":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4189,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4190,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Границы размещения","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние от внешней границы обочины, м","width":"20rem"},{"id":0,"name":"Name","code":"NAME","type":"owner","title":"Наименование","hasDate":false},{"id":4192,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true},{"id":4191,"name":"EmergencyRoom","code":"EMERGENCY_ROOM","type":"boolean","title":"Наличие травмпункта"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Принадлежность","width":"20rem"}],"multifunctional-zones":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4001,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м","hasDate":true},{"id":4146,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Границы размещения","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расстояние от внешней границы обочины, м","width":"20rem"},{"id":4003,"name":"GasStationCount","code":"AMOUNTOFGASSTATION","type":"number","title":"Количество АЗС, шт"},{"id":4004,"name":"ServiceStationCount","code":"NUMBEROFSERVICESTATIONS","type":"number","title":"Количество СТО, шт"},{"id":4005,"name":"HotelsCount","code":"NUMBEROFHOTELS","type":"number","title":"Количество гостиниц (мотелей, кемпингов), шт"},{"id":4006,"name":"FoodItemsCount","code":"NUMBEROFFOODITEMS","type":"number","title":"Количество пунктов питания, шт"},{"id":4007,"name":"WashingItemsCount","code":"NUMBEROFWASHINGPOINTS","type":"number","title":"Количество моечных пунктов, шт"},{"id":4008,"name":"ContactItemsCount","code":"NUMBEROFPOINTSOFCONTACT","type":"number","title":"Количество пунктов связи, шт"},{"id":4009,"name":"StoresCount","code":"NUMBEROFSTORES","type":"number","title":"Количество пунктов торговли, шт"},{"id":5384,"name":"Url","code":"URL","type":"string","title":"Интернет-сайт"}],"regulatory-statuses":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3495,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":3496,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":3497,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3920,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":3476,"name":"PlanFact","code":"PLAN_FACT","type":"boolean","title":"План\\\\факт"},{"id":0,"name":"Value","code":"VALUE","type":"number","title":"Значение","width":"10rem","children":[{"id":3478,"name":"LengthValue","code":"VALUE","type":"number","title":"км"},{"id":3886,"name":"NormPercentage","code":"NORM_PERCENTAGE","type":"number","title":"%"}]}],"diagnostics":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3488,"name":"Start","code":"START","type":"roadStartDiagnostics","title":"Начало участка, км+м"},{"id":3489,"name":"Finish","code":"FINISH","type":"roadFinishDiagnostics","title":"Конец участка, км+м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Координаты начала участка","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Координаты конца участка","width":"20rem"},{"id":3490,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Дата проведения обследования","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Тип дорожно-климатической зоны","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Техническая категория","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Тип дорожной одежды","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Рельеф местности","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Итоговое нормативное состояние, км","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Итоговое нормативное состояние, %","width":"20rem"}],"bridge-construction":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4105,"name":"IsChecked","code":"IS_CHECKED","type":"boolean","title":"Проверено"},{"id":0,"name":"Name","code":"FULL_NAME","type":"bridgeLink","title":"Наименование"},{"id":0,"name":"Id","code":"ID","type":"number","title":"Номер СКДФ"},{"id":4101,"name":"Start","code":"START","type":"string","title":"Начало, км+м"},{"id":4102,"name":"Finish","code":"FINISH","type":"string","title":"Конец, км+м"},{"id":4120,"name":"Type","code":"TYPE","type":"string","title":"Тип"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид материала","width":"20rem"},{"id":4122,"name":"TypeOfObstacle","code":"TYPE_OF_OBSTACLE","type":"string","title":"Тип основного препятствия"},{"id":4103,"name":"Length","code":"LENGTH","type":"number","title":"Полная длина, м"},{"id":4104,"name":"BuildingDate","code":"BUILDING_DATE","type":"date","title":"Год ввода в эксплуатацию","hasDate":true},{"id":4121,"name":"TechnicalCondition","code":"TECHNICAL_CONDITION","type":"string","title":"Техническое состояние"}],"pipes":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4114,"name":"IsChecked","code":"IS_CHECKED","type":"boolean","title":"Проверено"},{"id":0,"name":"Id","code":"ID","type":"number","title":"Номер СКДФ"},{"id":4110,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4129,"name":"TypeOfPipe","code":"PIPE_TYPE","type":"string","title":"Тип трубы"},{"id":4128,"name":"TypeOfObstacle","code":"TYPE_OF_OBSTACLE","type":"string","title":"Тип основного препятствия"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Полная длина, м","width":"20rem"},{"id":4112,"name":"BuildingDate","code":"BUILDING_DATE","type":"date","title":"Год ввода в эксплуатацию","hasDate":true},{"id":4127,"name":"TechnicalCondition","code":"TECHNICAL_CONDITION","type":"string","title":"Техническое состояние"}],"local-treatment-buildings":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3985,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Расположение","width":"20rem"},{"id":4672,"name":"Region","code":"REGION","type":"string","title":"Субъект РФ"},{"id":4050,"name":"Type","code":"TYPE","type":"string","title":"Тип","hasDate":true},{"id":3986,"name":"Quantity","code":"QUANTITY","type":"number","title":"Количество"},{"id":3987,"name":"Perfomance","code":"PERFORMANCE","type":"number","title":"Производительность, л/ч"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Техническое состояние","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Фотоматериалы","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Техническая документация","width":"20rem"}],"pedestrian-crossings":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":3927,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение"},{"id":4672,"name":"Region","code":"REGION","type":"string","title":"Субъект РФ"},{"id":4043,"name":"Type","code":"TYPE_OF_CROSSWALK","type":"string","title":"Тип","hasDate":true},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Длина, м","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Техническое состояние","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Фотоматериалы","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Техническая документация","width":"20rem"}],"photo-video-violation-fixation":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4420,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4425,"name":"InstallationLocation","code":"INSTALLATION_LOCATION","type":"string","title":"Расположение"},{"id":4426,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Направление"},{"id":4427,"name":"Type","code":"TYPE","type":"violationFixation","title":"Тип"},{"id":4416,"name":"SerialNumber","code":"SERIAL_NUMBER","type":"string","title":"Серийный номер"},{"id":4421,"name":"InstallationDate","code":"INSTALLATION_DATE","type":"date","title":"Дата установки"},{"id":4424,"name":"InstallationReason","code":"INSTALLATION_REASON","type":"string","title":"Причина установки"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Место установки","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид опоры","width":"20rem"}],"toll-points":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":4133,"name":"Location","code":"LOCATION","type":"string","title":"Местоположение, км+м"},{"id":4388,"name":"Direction","code":"DIRECTION_OF_TRAVEL","type":"string","title":"Расположение","hasDate":true}],"road-works":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":1972,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":1973,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":1851,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":2321,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":1657,"name":"TypeOfWorks","code":"TYPE_OF_WORKS","type":"string","title":"Вид работ"},{"id":1832,"name":"Deadline","code":"DEADLINE","type":"string","title":"Срок проведения"},{"id":0,"name":"SumZnach","code":"ZNACH","type":"number","title":"Предусмотрено, тыс.руб"},{"id":0,"name":"FinSource","code":"ISTOCHNIK_FINANCIROVANIYA","type":"string","title":"Источник финансирования"},{"id":0,"name":"Project","code":"PROJECT","type":"string","title":"Проект"},{"id":2127,"name":"WorkFinish","code":"WORK_FINISH","type":"date","title":"Дата завершения работ"}],"road-warranty-parts":[{"id":2008,"name":"Map","code":"MAP","type":"map","title":"","width":"3rem"},{"id":2055,"name":"Start","code":"START","type":"string","title":"Начало участка, км+м"},{"id":2056,"name":"Finish","code":"FINISH","type":"string","title":"Конец участка, км+м"},{"id":2057,"name":"Length","code":"LENGTH","type":"number","title":"Протяженность, км"},{"id":3917,"name":"Square","code":"SQUARE","type":"number","title":"Площадь покрытия проезжей части, кв.м"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Конструктивный элемент","width":"20rem"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Наличие гарантийных обязательств","width":"20rem"},{"id":2058,"name":"AssuranceStart","code":"ASSURANCE_START","type":"date","title":"Начало гарантии"},{"id":2059,"name":"AssuranceFinish","code":"ASSURANCE_END","type":"date","title":"Окончание гарантии"},{"id":0,"name":"Blank","code":"BLANK","type":"string","title":"Вид работ","width":"20rem"},{"id":0,"name":"Contractor","code":"CONTRACTOR","type":"owner","title":"Подрядчик"}]},"isChanged":false,"fetchState":"pending","_fields":[],"_visibleBlocks":[],"nav":{},"editMode":false}';
